const SET_GIRAFFES_INTO_AVIARY = 'giraffes/SET_GIRAFFES_INTO_AVIARY';
const ADD_AVIARY = 'giraffes/ADD_AVIARY';
const UPDATE_GIRAFFE = 'giraffes/UPDATE_GIRAFFE';
const EDIT_GIRAFFE = 'giraffes/EDIT_GIRAFFE';
export {
    SET_GIRAFFES_INTO_AVIARY,
    ADD_AVIARY,
    UPDATE_GIRAFFE,
    EDIT_GIRAFFE,
}
