const SET_GIRAFFES_INTO_AVIARY = 'giraffes/SET_GIRAFFES_INTO_AVIARY';
const ADD_AVIARY = 'giraffes/ADD_AVIARY';
const CREATE_GIRAFFE = 'giraffes/CREATE_GIRAFFE';
const UPDATE_GIRAFFE = 'giraffes/UPDATE_GIRAFFE';
const DELETE_GIRAFFE = 'giraffes/DELETE_GIRAFFE';
const EDIT_GIRAFFE = 'giraffes/EDIT_GIRAFFE';
const ADD_GIRAFFE = 'giraffes/ADD_GIRAFFE';
const SET_CURRENT_IMG = 'giraffes/SET_CURRENT_IMG';
const HIDE_CAPACITY = 'giraffes/HIDE_CAPACITY';
const CLOSE_ADDING_CARD = 'giraffes/CLOSE_ADDING_CARD';
const CLOSE_EDITING_CARD = 'giraffes/CLOSE_EDITING_CARD';

const SUCCESS = 'updatesHistory/SUCCESS';
const REJECTED = 'updatesHistory/REJECTED';
const NOT_CONFIRMED = 'updatesHistory/NOT_CONFIRMED';
const WAITING = 'updatesHistory/WAITING';

export {
    SET_GIRAFFES_INTO_AVIARY,
    ADD_AVIARY,
    CREATE_GIRAFFE,
    UPDATE_GIRAFFE,
    DELETE_GIRAFFE,
    EDIT_GIRAFFE,
    ADD_GIRAFFE,
    SET_CURRENT_IMG,
    HIDE_CAPACITY,
    CLOSE_ADDING_CARD,
    CLOSE_EDITING_CARD,
    SUCCESS,
    WAITING,
    NOT_CONFIRMED,
    REJECTED
}
