const SET_GIRAFFES_INTO_AVIARY = 'giraffes/SET_GIRAFFES_INTO_AVIARY';
const ADD_AVIARY = 'giraffes/ADD_AVIARY';
const CREATE_GIRAFFE = 'giraffes/CREATE_GIRAFFE';
const UPDATE_GIRAFFE = 'giraffes/UPDATE_GIRAFFE';
const EDIT_GIRAFFE = 'giraffes/EDIT_GIRAFFE';
const ADD_GIRAFFE = 'giraffes/ADD_GIRAFFE';
const SET_CURRENT_IMG = 'giraffes/SET_CURRENT_IMG';
const HIDE_CAPACITY = 'giraffes/HIDE_CAPACITY';

export {
    SET_GIRAFFES_INTO_AVIARY,
    ADD_AVIARY,
    CREATE_GIRAFFE,
    UPDATE_GIRAFFE,
    EDIT_GIRAFFE,
    ADD_GIRAFFE,
    SET_CURRENT_IMG,
    HIDE_CAPACITY
}
